# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57d1de2c5054442954c527c7b6e28d15f28e30a1d248359f52051e6d21fd25acc21350e98498fef2267e807adc91524d1f6435f0a142cb4a6546b9f61445950f

test:
  secret_key_base: 44325993746792883072f41e9323cc64e232735974d0f14f00dca71a801c4a4dc7be807e9a4245d4796b146d3f5fb75d0ab8a4e969841b74420dcf256bf3d02c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
